log_level: <%= ENV.fetch('LOG_LEVEL', 'error') %>

telegram:
  token: <%= ENV['TELEGRAM_BOT_TOKEN'] %>

scheduler:
  application_id: <%= ENV['SCHEDULER_APPLICATION_ID'] %>
  api:
    host: <%= ENV['SCHEDULER_API_HOST'] %>
    secret: <%= ENV['SCHEDULER_API_SECRET'] %>

docker:
  image:
    name: scheduler_bot
    host: ghcr.io
    owner: <%= ENV['DOCKER_IMAGE_OWNER'] %>

stages:
  development:
    dockerfile: Dockerfile

  production:
    dockerfile: Dockerfile.production
    remote:
      user: app
      host: scheduler.iskrenkov.com
      root: /var/www/scheduler_bot/
